---
- name: Gather User Facts
  hosts: all
  become: no
  roles:
      - user

- name: Developer Machine (root)
  hosts: all
  become: yes
  roles:
    - common-packages
    - rpmfusion
    - ansible
    - flatpak
    - php
    - composer
    - docker
    - google-chrome
    - atom
    - wireguard
  vars:
      composer_home_owner: "{{ login_user }}"
      composer_home_group: "{{ group_name }}"
      composer_global_packages:
          - { name: friendsofphp/php-cs-fixer }
          - { name: pyrech/composer-changelogs }


- name: Developer Machine (user)
  hosts: all
  become: no
  roles:
      - firefox
      - nodejs
      - phpstorm
      - slack
      - android-studio
