---
- name: Install Flatpak
  dnf:
    name: flatpak
    state: latest

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Check If Plasma Discover Is Installed
  package:
    name: plasma-discover
    state: present
  check_mode: true
  register: discover_check

- name: Install Plasma Discover Flatpak Plugin
  dnf:
    name: plasma-discover-flatpak
    state: latest
  when: not discover_check.changed
