---
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Adding user to docker group
  user:
    name: "{{ login_user }}"
    groups: docker
    append: yes

- name: Installing docker compose
  pip:
    name: docker-compose
    state: latest

- name: Enable docker
  systemd:
    name: docker
    enabled: yes
    state: started
