---
- name: Add Docker Repository
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: "https://download.docker.com/linux/fedora/{{ ansible_distribution_version }}/$basearch/stable"
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: true
    gpgcheck: true
  register: dockerrepo_install

- name: dnf cache
  dnf: update_cache=yes
  when: dockerrepo_install.changed

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  register: docker_install

- name: Enable backward compatibility for Cgroups v1
  shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when: docker_install.changed

- name: Switch firewalld to iptables
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^FirewallBackend=nftables'
    line: 'FirewallBackend=iptables'
  notify: restart firewalld
