---
- name: Install Docker Repository Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    state: latest

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Adding user to docker group
  user:
    name: "{{ login_user }}"
    groups: docker
    append: yes

- name: Installing docker compose
  pip:
    name: docker-compose
    state: latest
