---
- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Firefox
  flatpak:
    name: org.mozilla.firefox
    state: present
    method: user
    remote: flathub
  register: firefox_install

- name: Remove Firefox
  dnf:
    name: firefox
    state: absent
  become: true
