- name: Enable the RPM Fusion repository free
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    update_cache: true
    disable_gpg_check: true

- name: Enable the RPM Fusion repository non-free
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    update_cache: true
    disable_gpg_check: true

- name: Update core group
  dnf:
    name: '@core'
    state: latest

- name: Multimedia post-install (gstreamer)
  dnf:
    name: '@multimedia'
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin
    state: latest

- name: Multimedia post-install (sound-and-video)
  dnf:
    name: '@sound-and-video'
    state: latest

- name: Install rpmfusion-free-release-tainted
  dnf:
    name: rpmfusion-free-release-tainted
    state: present
