---
- name: Add Atom Repository
  yum_repository:
    name: atom
    description: Atom YUM repo
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
  register: atom_repo_install

- name: dnf cache
  dnf: update_cache=yes
  when: atom_repo_install.changed

- name: Install Atom
  dnf:
    name: atom
    state: latest
